/control/verbose 2
/run/initialize

# -------------------------------

# -------------------------------
/analysis/setFileName NCD_0.0001MeV_Neutrons_1inchPE.root
/analysis/openFile 
/gps/particle neutron
/gps/ene/mono 0.00001 MeV
# Water boxes 70 -25 0, PolyEthylene 70 -55 0 cm 
/gps/position 70 -60.08 0 cm 
/gps/pos/type Point
# 3. Emit in **random directions**
/gps/ang/type iso        # isotropic emission
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 180 deg

/gps/ang/minphi 0 deg
/gps/ang/maxphi 360 deg

/run/beamOn 3000000
/analysis/closeFile

